### ISSUE TITLE
WhisperSystems/libsignal-protocol-java on lgtm.com

### ISSUE THREAD

**Issue by aibaars** [katrielalex/stupid-copy-that-isnt-a-fork-of-libsignal-protocol-java#1]
Thanks for your interest in lgtm.com . I added WhisperSystems/libsignal-protocol-java to lgtm.com using a manual build configuration (see below). You can view the results on https://lgtm.com/projects/g/WhisperSystems/libsignal-protocol-java/ . The project appears to be of very high quality (no warnings or errors). Great work guys!
```
extraction:
  java:
    before_index: rm -f tests/src/test/java/org/whispersystems/libsignal/fingerprint/NumericFingerprintGeneratorTest.java
    index:
      build_command: ./gradlew --no-daemon -S testClasses -PsonatypeRepo=http://example.com -PwhisperSonatypeUsername=user -PwhisperSonatypePassword=secret -x uploadArchives
```
